### ISSUE TITLE
Error in `easy-fs-fuse` When Writing Large Data in a Single Operation

### ISSUE THREAD

**Issue by 13m0n4de** [13m0n4de/lemon-core#4]
## Problem Description

In `easy-fs-fuse`, attempting to write a very large amount of data at once can lead to EFS not loading properly or causing the FUSE program to crash.

This problem was identified after adding the `indirect3` feature.

### Problem 1

Writing a file larger than 8M in one go (specifically, a file that exceeds the total size of 2-level indirect indexes, which is 13.5KiB + 64KiB + 8MiB) results in:

```
dd if=/dev/zero bs=9M count=1 > easy-fs-root/testfile
```

This action triggers a FUSE panic:

```
thread 'main' panicked at src/block_file.rs:13:9:
assertion `left == right` failed: Not a complete block!
  left: 0
 right: 512
```

### Problem 2

Changing from a single large write to multiple smaller writes.

Modify:

https://github.com/13m0n4de/lemon-core/blob/6501875cfbae7b9919a64cfe5ff4a4bb5815c347/easy-fs-fuse/src/main.rs#L72-L77

To:

```rust
let mut file = File::open(&entry_path)?;
let inode = parent_inode.create(entry_name).unwrap();

let mut buffer = vec![0; 65536];
let mut offset = 0;
loop {
    let bytes_read = file.read(&mut buffer)?;
    if bytes_read == 0 {
        break;
    }
    inode.write_at(offset, &buffer[..bytes_read]);
    offset += bytes_read;
}
```

- When `buffer` is set to `99617`, FUSE does not panic, and files larger than 9M can be written.
- When `buffer` is set to `99618`, FUSE does not panic, but the kernel encounters a filesystem loading error at startup:

	```
	[ERROR] [kernel] Panicked at easy-fs/src/efs.rs:96 Error loading EFS!
	```

## Possible Solution

Writing in chunks with an appropriately sized buffer does not cause issues and can be used as a temporary solution:

```rust
let mut file = File::open(&entry_path)?;
let inode = parent_inode.create(entry_name).unwrap();

let mut buffer = vec![0; 65536];
let mut offset = 0;
loop {
    let bytes_read = file.read(&mut buffer)?;
    if bytes_read == 0 {
        break;
    }
    inode.write_at(offset, &buffer[..bytes_read]);
    offset += bytes_read;
}
```

**Comment by 13m0n4de** [comment]
Temporary solutions are not applied to `ch6` - `ch9` branches until the exact problem is found, nor are they necessary (there is no single application that large)

**Comment by 13m0n4de** [comment]
I discovered another problem when reading a 17MB file, which leads to a new error:

https://github.com/13m0n4de/lemon-core/blob/bbc2856fbcd32fe908d3711e34e010a9850a6f43/easy-fs/src/layout.rs#L295-L300

```
Packing files from "../easy-fs-root/" into the easy-fs image...
thread 'main' panicked at easy-fs/src/layout.rs:299:33:
index out of bounds: the len is 128 but the index is 128
```

**Moreover, in the official eBook's implementation, the same issue occurs at the same location**, but it happens with an 8MB file.

**Comment by 13m0n4de** [comment]
> when reading a 17MB file

This problem should not be caused by FUSE. After the kernel is started, the same problem will occur when writing files larger than 16MB using user programs.

**Comment by 13m0n4de** [comment]
All branches cancel the implementation of the 3-level indirect block, until it stabilizes in the `features/easy-fs-indirect3` branch.
